### ISSUE TITLE
¿Plugin sigue en desarrollo?

### ISSUE THREAD

**Issue by machelinos** [open-pay/openpay-woosubscriptions#1]
Hola, lo he probado en mis sitios de prueba, tanto con mi theme como con store front, sin embargo no me funciona con la versión más reciente de Woocommerce y Subscriptions, ¿Tienen planeado actualizarlo?

**Comment by fedebalderas** [comment]
Que versiones tienes?

**Comment by machelinos** [comment]
Subscriptions 2.1.2 y Woocommerce 2.6.11

**Comment by fedebalderas** [comment]
Acabamos de subir la última versión que tenemos, cabe mencionar que esta probada con WooSubscriptions v2.1.0 y WooCommerce 2.6.8

Te recomiendo desinatalar y eliminar el plugin que tienes de Openpay e instales esta nueva versión. Si aún tienes problemas te pediría que me facilites la versión de Subscriptions que tienes para probar.

Saludos!

**Comment by machelinos** [comment]
gracias por su respuesta, ya lo descargué y lo estoy probando pero me sigue marcando el siguiente error en el frontend al momento de intentar hacer una compra de prueba "1001 Los campos no tienen el formato correcto, o la petición no tiene campos que son requeridos." Lo estoy haciendo con el theme Store front como prueba y las versiones que me comentas que est{an soportadas: Woocomerce 2.6.8 y Subscriptions 2.1.0, en los logs de Openpay me aparece que si crea el customer y el token, pero al momento de crear la tarjeta arroja el error "400 Bad Request" en la llamada solo envía el token_id y en la respuesta aparece " "description": "Attribute device_session_id is required"," no se si les sirva mejor copiar el código completo o ustedes lo puedan reproducir el error. Gracias, saludos.

**Comment by fedebalderas** [comment]
Tienes la plataforma en línea o todo lo tienes local? Y si pudieras pasarme tu acceso a la cuenta de Sandbox de Openpay para checar los logs de favor. Te paso mi correo: federico.balderas@openpay.mx

**Comment by machelinos** [comment]
Está en línea un site de prueba test, te acabo de enviar el acceso al sandbox y la liga al sitio de prueba, gracias!

**Comment by fedebalderas** [comment]
Se actualizó el repositorio con la corrección.

**Comment by joseamijares** [comment]
Hola tengo woocommerce subscriptions última versión y problemas con open pay, en los logs me sale:
    "category": "request",
    "description": "Attribute device_session_id is required",
    "http_code": 400,
    "error_code": 1001,
    "request_id": "2d7844c8-8d92-4e23-80bf-f2338b5eeb7f"
}

**Comment by machelinos** [comment]
Hola @joseamijares, tuve el mismo problema, openpay no está actualizando el plugin, la respuesta que me dieron fue regresarme a la version de subscriptions de hace un año, lo cual simplemente no podemos hacer, te recomiendo buscar otra pasarela de pagos o desarrollar tu mismo la conexión porque su plugin para subscriptions no funciona y según sus respuestas que me dieron no piensan actualizarlo proactivamente.

**Comment by joseamijares** [comment]
Hola @machelinos gracias por la información que mal que no actualicen sus sistema y que nosotros por seguridad actualizamos los demás plugins y ellos no hagan su parte.
@fedebalderas alguna novedad con este tema?

**Comment by fedebalderas** [comment]
Que tal @joseamijares , la última versión sobre la cual esta probado el plugin es: WooSubscriptions v2.2.7. Supondría que en todo caso tienes la 2.2.12, cierto?

Pregunta... este error te lo arroja cuando pruebas ya el cargo recurrente como se menciona en este enlace https://docs.woocommerce.com/document/testing-subscription-renewal-payments/?

De ser así, los comercios que integran WooSubscription deben contactar a Soporte (soporte@openpay.mx) para que realicen una configuración sobre tu comercio (tanto sandbox como productivo) y no te pida ese "device_session_id" al tratar de realizar el cargo, como ves?

**Comment by machelinos** [comment]
Hola @fedebalderas yo hice lo de escribir a soporte@openpay.mx para esa configuración, como tu me lo comentaste en el otro issue que abrí, pero no hicieron nada de esa configuración, les expliqué exactamente lo que tu me dijiste y me dijeron que era porque tenía una versión muy nueva de los plugins y que efectivamente no lo actualizan proactivamente.

**Comment by fedebalderas** [comment]
@machelinos No, en este caso del tema del device_session_id es por esta configuración que te comenté y que le comento a @joseamijares.
Si quieres pásenme por correo la cuenta de correo con que tienen registrado su comercio y yo le paso el dato directo a Soporte.

**Comment by machelinos** [comment]
Listo @fedebalderas ya te mandé el correo de la cuenta a tu correo, me pudieras confirmar cuando hayan hecho el ajuste por favor, para hacer las pruebas nuevamente y te comento el status en cuanto lo cheque.

**Comment by joseamijares** [comment]
@fedebalderas gracias por la respuesta.
El primer cargo me lo hace bien, pero a la hora de hacer el cobro de nuevo me aparece ese error en el log de openpay: 

{
    "category": "request",
    "description": "Attribute device_session_id is required",
    "http_code": 400,
    "error_code": 1001,
    "request_id": "b728126c-a788-44ab-a353-f855f0def0c6"
}

Mi merch id es: mfriuvpvzgboxwwkuhbn

Ahorita envío el correo pero me urge resolver esto.

**Comment by joseamijares** [comment]
@fedebalderas ya envie el correo por favor te pido tu apoyo muchas gracias!

**Comment by joseamijares** [comment]
@machelinos si logras resolverlo por favor me dices, de igual manera yo.

**Comment by joseamijares** [comment]
@fedebalderas una duda por lo que entiendo entonces no hay manera de que sirva para nadie este sistema de pago con suscripciones no? entonces deberían de poner un aviso en el plugin o cuando tienes la llamada con openpay te deberían de decir esta info porque muchas personas no saben usar github y encontrar al desarrollador, te lo doy como tip de servicio al cliente.

**Comment by joseamijares** [comment]
Hola @fedebalderas  no me han contestado nada de open pay, hay manera de darle seguimiento a esto?

**Comment by fedebalderas** [comment]
@joseamijares la configuración fue realizada desde el día Viernes.

Saludos!

**Comment by joseamijares** [comment]
Hola pero si fue desde el viernes tengo que la suscripción se intente una vez al día y ayer tampoco paso:
![screen shot 2017-09-25 at 9 50 47 am](https://user-images.githubusercontent.com/6046480/30814880-0cd51baa-a1d7-11e7-9436-8a8e17953773.png)

**Comment by joseamijares** [comment]
Volví a hacer dos pruebas que en 55 min pasan te aviso cualquier cosa, muchas gracias de verdad por el apoyo.

**Comment by joseamijares** [comment]
Hola @fedebalderas , me arrojo de nuevo un error
![screen shot 2017-09-25 at 10 51 39 am](https://user-images.githubusercontent.com/6046480/30817828-903baa1a-a1df-11e7-9eaa-f11cce1061be.png)

**Comment by rivaldoleon** [comment]
@joseamijares Pudiste resolver el error? Justamente me pasa lo mismo, pero ahora ni el módulo de Cards funciona, arroja el mismo error.

**Comment by rivaldoleon** [comment]
@fedebalderas Que tal, hice lo que comentas de escribir un correo a soporte para que deshabiliten una configuración, y me contestaron y ya quedó eso. Ahora lo que pasa es que no genera la info de la tarjeta y genera un error.
![captura de pantalla 2017-09-29 a la s 21 22 15](https://user-images.githubusercontent.com/21352803/31041565-fa1e7d60-a55c-11e7-8c1e-b69fc3bcef55.png)

**Comment by fedebalderas** [comment]
@rivaldoleon Cuando el token de la tarjeta no es generado desde el momento en que se registra la suscripción es porque el JS que tokeniza no esta esta funcionando, esto puede ser por varios motivos:

- No se están cargando las librerías (raro porque dices que antes hacía esto)

- Porque algún otro JS ya sea de otro plugin o bien del template instalado en la tienda le mete ruido y no hace su función el JS del plugin de Openpay.

Has revisado la consola de tu navegador para ver que errores te arroja?

**Comment by rivaldoleon** [comment]
@fedebalderas Gracias por la respuesta. Tengo instalada la última versión de Openpay-Cards (3.0.8) y la última versión de Openpay-Woosubscriptions. Si desactivo Openpay-Woosubscriptions, el módulo de Openpay-Cards funciona bien, y viceversa, si desactivo Openpay-Cards, el módulo Openpay-Woosubscriptions funciona bien. Fueron las últimas pruebas que estuve haciendo y Woosubscriptions ya funciona bien, que al final es lo que me interesa. Hace el cobro de productos regulares y de suscripciones. Y genera bien los cargos recurrentes (ya probé esa parte también).

Si dejo activo los dos módulos y quiero hacer un pago por Openpay-Cards, el error que genera es:
Undefined index: openpay_token in .../store/wp-content/plugins/openpay-cards/openpay_cards_gateway.php on line 285.

**Comment by fedebalderas** [comment]
Como mencionas... el de plugin suscripciones hace los cobros regulares así como las suscripciones. Creo que no me ha tocado hacer un ejercicio donde convivan ambos pero probablemente si se metan ruido por el nombre las clases, igual lo revisamos para no dejarlo pasar, gracias por la observación.

Saludos!

**Comment by joseamijares** [comment]
Hola @rivaldoleon  @fedebalderas  si yo ya tengo el plugin funcionando correctamente al parecer si era el tema de configuración de su parte.

**Comment by JGTI** [comment]
Les dejo la solución a todos 

remplaza este archivo en /wp-content/plugins/openpay-cards/openpay_cards_gateway.php 
https://github.com/JGTI/openpay-wordpress-solucion/blob/main/openpay_cards_gateway.php
