### ISSUE TITLE
Renovacion Fallida The CVV2 security code is required

### ISSUE THREAD

**Issue by Kersei** [open-pay/openpay-woosubscriptions#10]
Saludos, me aparecio este error cuando se intentaron hacer las renovaciones:
{
    "category": "gateway",
    "description": "The CVV2 security code is required",
    "http_code": 400,
    "error_code": 2006,
    "request_id": "id"
}

el pago inicial para esta suscribcion se hizo correctamente, este error aparecio al intentarse la renovacion.

la llamada fue la siguiente:
{
    "amount": "999.00",
    "currency": "mxn",
    "description": "Suscripci\u00f3n \"SUSCRIPCI\u00d3N FITNESS ON DEMAND\" (Order 12321)",
    "method": "card",
    "order_id": "id",
    "source_id": "id"
}

espero puedas ayudarme.

**Comment by fedebalderas** [comment]
@Kersei debes solicitar al equipo de soporte (soporte@openpay.mx) que configuren a tu comercio (ambiente de sandbox y productivo) los cargos recurrentes. Coméntales que estas utilizando el plugin de suscripciones de WooCommerce.

Saludos!

**Comment by Kersei** [comment]
Ya tengo configurado eso, tanto en sandbox como en produccion. Ya habia hecho pruebas con cargos recurrentes pero esto recien me paso con un cliente, igual ya me puse en contacto con ellos, a ver si ellos saben porque esta pasando esto, agradezco tu pronta respuesta.

Saludos

**Comment by fedebalderas** [comment]
@Kersei De ser así, creo que a veces ya tiene que ver con tema de cada banco pero si es tema ya del core de Openpay y no tanto del plugin. Igual cualquier cosa me dices.

Saludos!

**Comment by Kersei** [comment]
@fedebalderas ya estuve enviándome correos con los de soporte, ellos dicen que el problema es mi version de woocommerce subscription y que debo hacer un downgrade, el problema es que los de woocommerce no me dan acceso a versiones anteriores del plugin, en realidad no entiendo porque es un problema si ya había realizado pruebas con anterioridad y los pagos recurrentes se estaban haciendo correctamente, hasta que versión de woocommerce subscription soporta tu plugin?

Saludos.

**Comment by fedebalderas** [comment]
Que tal @Kersei,  No es problema con el plugin, el plugin hace su trabajo como debe de... como puedes ver el error es por un tema de CVV requerido, esto es porque como tal no se debe de guardar nunca ese dato, por ende es imposible mandarlo, sin embargo hay una configuración en Openpay a nivel comercio que evita solicitar ese dato para transaccionar (a menos que ya lo hayan cambiado y no lo sepa).

Deja les envío un correo directamente, pudieras compartirme el ID de tu comercio y el nombre por favor.

**Comment by Kersei** [comment]
Sale muchas gracias, te paso los datos que necesitas:

Comercio: INSPIRING FITNESS
ID: mnynbhit5ytreis4fqvz

**Comment by fedebalderas** [comment]
Que hay @Kersei, me comentan que no tenía bien dicha configuración, si gustas probar y me confirmas porfa.

Saludos!

**Comment by Kersei** [comment]
@fedebalderas perdona por la tardanza, ya realice varias pruebas y ya se estan haciendo las renovaciones correctamente, te agredezco mucho la ayuda. Solo estoy teniendo un problema con unas tarjetas pero no se si ponertelo aqui o hacer otro issue?

Saludos

**Comment by fedebalderas** [comment]
@Kersei  Pero que tipo de problema? Cabe mencionar que hay veces que no pasan los cargos de algunas tarjetas y pues ahí no hay mucho que hacer, ya esta del banco emisor, etc.

**Comment by Kersei** [comment]
@fedebalderas me esta apareciendo un error 1005 con unas tarjetas de Santander, sabes a que se debe?

**Comment by fedebalderas** [comment]
Podrías poner una imagen de tu petición/respuesta para estar en el mismo canal?

**Comment by Kersei** [comment]
Aqui esta la peticion, nunca llega a openpay

{
"result":"failure",
"messages":"<ul class=\"woocommerce-error\" role=\"alert\">\n\t\t\t<li>Error: \"1005 Servicio no disponible.\"<\/li>\n\t<\/ul>\n",
"refresh":false,
"reload":false
}
![imagen](https://user-images.githubusercontent.com/22964489/42665323-bdf8abba-8604-11e8-8312-e5f9b37f551e.png)

**Comment by fedebalderas** [comment]
Pero entonces es cuando el usuario apenas ingresa sus datos de la tarjeta, no cuando es el cargo recurrente, correcto?

**Comment by Kersei** [comment]
@fedebalderas si exacto es al intentar el primer pago

**Comment by fedebalderas** [comment]
Me da la impresión que el problema es con algún usuario con el cual hiciste pruebas en modo sandbox y se le asoció un ID de cliente Openpay en tu BD, ahora que cambiaste a modo productivo (o viceversa) trata de realizar la transacción utilizando ese ID de cliente Openpay y no lo encuentra en el ambiente en el que estas ahora. Esto es lo más probable que este pasando.

**Comment by Kersei** [comment]
Si al parecer ese era el problema, intente hacer el pago con la misma tarjeta solo con otro usuario y paso correctamente, nuevamente te agradezco mucho tu ayuda, y paso a cerrar esto.

Saludos!
