### ISSUE TITLE
ERROR undefined. La petición no pudo ser procesada.

### ISSUE THREAD

**Issue by jaime-md** [open-pay/openpay-woosubscriptions#11]
Gracias por su ayuda.

El —ERROR undefined. La petición no pudo ser procesada— sucede cada vez que desde la página de pago hago click en el botón "Sign Up Now" de mi custom theme para intentar procesar el pago.

El error sucede en mi tema custom, pero también he comprobado que sucede en otros temas oficiales preparados para WooCommerce.

La tarjeta ficticia de sandbox que utilizo: 4111 1111 1111 1111

Mi ambiente:
• Copia local en localhost con certificado SSL de prueba
• Instalación limpia de Wordpress 4.9.8
• WooCommerce 3.4.4
• WooCommerce Subscriptions 2.3.3
• Openpay WooSubscriptions Plugin 2.7.1
• "Forzar pago seguro" habilitado

**Comment by Urano-Gonzalez** [comment]
A mi pasó esto si tengo el plugin de tarejtas y el de suscripciones al mismo tiempo

**Comment by cristophergv** [comment]
Como pudieron resolverlo?. Tambien tengo tarjetas y suscripciones.

**Comment by fedebalderas** [comment]
@cristophergv como menciona @Urano-Gonzalez , los 2 plugins no puede convivir juntos.

**Comment by cristophergv** [comment]
Es decir WooCommerce Subscriptions y Openpay WooSubscriptions  no pueden trabajar en conjunto cual es el objetivo?.

**Comment by fedebalderas** [comment]
@cristophergv no, a lo que se refiere Urano es que el plugin de "Pago tarjetas de Openpay" y el plugin de "Suscripciones de Openpay" no pueden estar habilitados al mismo tiempo. Son 2 plugins diferentes de Openpay, que chocan al estar habilitados en una tienda el mismo tiempo.

**Comment by Urano-Gonzalez** [comment]
Si vas a usar suscripciones,  usas el plugin "suscripciones de Openpay", si no, usas el "pago tarjetas de openpay"
