### ISSUE TITLE
Actualizar tarjeta para un pago de suscripción

### ISSUE THREAD

**Issue by pilimoguel91** [open-pay/openpay-woosubscriptions#12]
Hola! Al querer actualizar la tarjeta de crédito o débito en mi cuenta, sólo da la opción de cambiar el método de pago a PayPal, pero no me aparece la opción de seguir pagando la suscripción con OpenPay, pero cambiar de tarjeta ¿sabes por qué se da esto? ¿hay que hacer algo para que funcione?

Gracias!

**Comment by fedebalderas** [comment]
@pilimoguel91 el plugin actualmente no soporta el cambio de tarjeta para las suscripciones. Una vez que realizaste la suscripción con una tarjeta, esta permanecerá por todo el tiempo de vida de la suscripción.

**Comment by jose-openpay** [comment]
La funcionalidad del cambio de tarjeta para las suscripciones se agregó a la nueva versión disponible del plugin.

**Comment by jose-openpay** [comment]
La funcionalidad del cambio de tarjeta para las suscripciones se agregó a la nueva versión disponible del plugin.
