### ISSUE TITLE
Soporte versiones Woocommerce

### ISSUE THREAD

**Issue by pilimoguel91** [open-pay/openpay-woosubscriptions#13]
Hola! 

Quisiera saber cuál es la última versión soportada de woocommerce, para saber si puedo actualizar a Wordpress 5 y Woocommerce 3.5

¡Gracias!

**Comment by fedebalderas** [comment]
@pilimoguel91 te comento que la última versión sobre la cual esta probado es:

- Wordpress v4.9.8

- WooCommerce v3.5.0

**Comment by pilimoguel91** [comment]
Hola @fedebalderas ¿hay alguna actualización?
