### ISSUE TITLE
Reintentar cobreo de suscripción

### ISSUE THREAD

**Issue by pilimoguel91** [open-pay/openpay-woosubscriptions#14]
¿Hay alguna forma de reintentar un cobro a la tarjeta cuando se rechaza un pago por suscripción?

Gracias

**Comment by fedebalderas** [comment]
@pilimoguel91 Como tal no existe una funcionalidad que haga esto, aunque tal vez modificando el estatus de la orden y cambiando la fecha de renovación, probablemente así se le pueda dar vuelta al asunto, pero vaya no estoy 100% seguro pero me haría sentido.
