### ISSUE TITLE
Versiones soportadas

### ISSUE THREAD

**Issue by pilimoguel91** [open-pay/openpay-woosubscriptions#15]
Hola!

Quisiera saber si hay alguna actualización en la última versión soportada de woocommerce, para saber si puedo actualizar a Wordpress 5 y Woocommerce 3.5

¡Gracias!

**Comment by fedebalderas** [comment]
@pilimoguel91 la última versión sobre la que esta testeado el plugin es WooCommerce v3.5.5 y Wordpress v5.0.3.

Saludos!

**Comment by pilimoguel91** [comment]
Hola. ¿Me podrías decir cuál es la última versión soportada para WooCommerce y Wordpress?

Gracias
