### ISSUE TITLE
No se logra la renovación de suscripciones

### ISSUE THREAD

**Issue by Urano-Gonzalez** [open-pay/openpay-woosubscriptions#16]
Hola.
Estoy en desarrollo de una tienda con suscripciones.
el error que envía es:
{
    "http_code": 400,
    "error_code": 1001,
    "category": "request",
    "description": "Attribute device_session_id is required",
    "request_id": "43bae79c-5b73-45bc-997a-c35e4898f693"
}

Parecería que está esperando una compra normal y no un cargo recurrente

**Comment by fedebalderas** [comment]
@Urano-Gonzalez así es, porfa mándale un correo a soporte (soporte@openpay.mx) y coméntales que vas a utilizar el plugin de openpay-woosubscriptions para que te realicen una configuración sobre tu comercio y que ya no te pida este atributo en la petición recurrente.

OJO... esta configuración es por ambiente, por lo cual deberás de solicitarlo tanto para sandbox si estas realizando pruebas y después cuando pases a producción lo mismo.
