### ISSUE TITLE
El plugin no funciona en Woocommerce 3.9.1

### ISSUE THREAD

**Issue by Kersei** [open-pay/openpay-woosubscriptions#17]
Buen día Federico, 

Actualicé a la versión más reciente de WooCommerce 3.9.1 en Wordpress 5.3.2 y ya no me deja pagar con el plugin, me aparece el siguiente error:

![imagen](https://user-images.githubusercontent.com/22964489/73857122-16519f00-47fc-11ea-90ef-bd7f09466b59.png)

podrías ayudarme a resolverlo o en su defecto decirme cual es la versión máxima donde funciona el plugin? gracias de antemano.

**Comment by Urano-Gonzalez** [comment]
Hola @Kersei .  Pudiste resolverlo?
