### ISSUE TITLE
Modulo no crea planes de suscripcion

### ISSUE THREAD

**Issue by cjm900** [open-pay/openpay-woosubscriptions#18]
tengo la ultima version de woocomerce, tambien de woocomerce suscriptions,
incluso en mi escritorio dice que este plugin es compatible para pagos recuerrentes sin embaro el modulo solo procesa el pago, es decir, en la llamada solo crea la instruccion del cargo, en mi dashboard de openpay no crea ningun plan de suscripcion ni tampoco liga al cliente, solo procesa el cargo inicial.
espero su ayuda
gracias

**Comment by fedebalderas** [comment]
@cjm900 , este funcionamiento es correcto. Lo que pasa es que para como funciona WooSubscriptions, ellos gestionan tareas programadas que cada que se llega a la fecha de renovación disparan una acción para realizar un siguiente cobro, por eso es que en Openpay no se genera ningún tipo de plan, ya que WooSubscriptions es el que se encarga de ejecutar los cobros recurrentes. Lo que si debes de hacer es solicitar al equipo de soporte de Openpay (soporte@openpay.mx) que te habiliten los "cargos recurrentes programados", de otro modo cuando WooSubscriptions trate de hacer el cobro de forma automatizada Openpay lo va a rechazar, diles que utilizas el plugin de **openpay-woosubscriptions**.
