### ISSUE TITLE
Pago recurrente no se aplica en entorno de pruebas

### ISSUE THREAD

**Issue by machelinos** [open-pay/openpay-woosubscriptions#2]
Hola, estoy realizando pruebas en sandbox, pero me aparece el problema que una vez que se hace el primer pago, los siguientes pagos recurrentes de la suscripción no se aplican, el error que me da el dashboard de openpay es el siguiente:

Estado
400 Bad Request
Fecha
miércoles 23 de agosto del 2017, 09:46:56
ID
d71b5f5f-4f03-42b7-ad99-f01062504491
IP
50.87.144.115
User Agent
Parámetros
58
Llamada
{
    "amount": "200.00",
    "currency": "mxn",
    "description": "Suscripci\u00f3n \"Promocionado\" (Order 402)",
    "method": "card",
    "order_id": "402_20170823_144655",
    "source_id": "kboawcmzxotgbyy7lqan"
}
Respuesta
{
    "category": "request",
    "description": "Attribute device_session_id is required",
    "http_code": 400,
    "error_code": 1001,
    "request_id": "d71b5f5f-4f03-42b7-ad99-f01062504491"
}

2.- Otra duda que tengo, el primer pago pasa bien, sin embargo n woocommerce el pedido no se marca como completado ¿hay algun hook que se envíe a woocommerce para marcar el pago como completado? ya que en el entorno de pruebas solo lo puedo hacer manualmente.

Gracias!

**Comment by fedebalderas** [comment]
Que tal @machelinos,
Para los comercios que utilizan un modelo de Suscripciones (o cargos recurrentes programados), deberás de solicitar a Soporte (soporte@openpay.mx) que deshabiliten una configuración a tu comercio (tanto en sandbox como cuando pases a producción) para que estos cargos puedan pasar sin problema.

Saludos!
