### ISSUE TITLE
Establecer ID del Plan de Suscripción

### ISSUE THREAD

**Issue by andresamayadiaz** [open-pay/openpay-woosubscriptions#3]
¿Nos podrían indicar en qué lugar se establece el ID del Plan de la Suscripción?
Al parecer realiza la compra como si fuera pago único.

**Comment by fedebalderas** [comment]
@andresamayadiaz Que hay Andrés, es correcto... Esto funciona así debido a que WooCommerce internamente maneja un "calendario" con las fechas de pago... entonces lo que hace es que en ese día laza el cobro, por eso es que se realiza como "pago único" y no se crea ninguna suscripción en Openpay ni mucho menos. 

Cabe mencionar que si ocupas este plugin, debes solicitar a soporte@openpay.mx que te realicen cierta configuración sobre tu comercio, tanto en modo Sandbox como cuando pases a Productivo para que se puedan realizar estos "pagos únicos" pero recurrentes.

Saludos!
