### ISSUE TITLE
No funciona

### ISSUE THREAD

**Issue by rockdrigo** [open-pay/openpay-woosubscriptions#4]
el primer cobro si lo hace de forma correcta, pero al momento de hacer el cargo recurrente aparece lo siguiente:

{
    "category": "request",
    "description": "Attribute device_session_id is required",
    "http_code": 400,
    "error_code": 1001,
    "request_id": "(numero de request ID)"
}

Al parecer el device_session_id es necesario para su herramienta antifraude, pero al ser recurrente el cobro ya no se genera un device_session_id nuevo, como solucionamos esto???

**Comment by fedebalderas** [comment]
@rockdrigo debes de solicitar a soporte que realicen una configuración en tu Comercio para que no solicite este dato en el cargo recurrente, tanto para ambiente de sandbox como para productivo. Te dejo el correo soporte@paynom.mx

Saludos!

**Comment by rockdrigo** [comment]
@fedebalderas  gracias, ya les he escrito, les tengo que pedir algo en particular o solo que me ayuden con el plugin y ellos saben que hacer?? soporte@paynom.mx es lo msimo que OpenPay? gracias!

**Comment by fedebalderas** [comment]
@rockdrigo diles que necesitas que te configuren el comercio para que pasen los cargos recurrentes de WooSubscriptions.
