### ISSUE TITLE
la tarjeta registrada error The CVV2 security code is required

### ISSUE THREAD

**Issue by rockdrigo** [open-pay/openpay-woosubscriptions#5]
Mi cliente ya hizo su primer cargo, ya avise a soporte que usaria el plugin pero al intentar cobrar da el error de: The CVV2 security code is required

respuesta
{
    "category": "gateway",
    "description": "The CVV2 security code is required",
    "http_code": 400,
    "error_code": 2006,
    "request_id": "(numero de request ID)"
}

que debo de hacer para que el pago se procese sin problemas?

**Comment by fedebalderas** [comment]
Que tal @rockdrigo,
Por lo que dices ya realizó su primer cargo, entonces a que te refieres con "al intentar cobrar"? Ya le estas realizando el cargo recurrente? 

Podrías compartir también la petición como es enviada?

**Comment by rockdrigo** [comment]
@fedebalderas  si, ya se hizo el primer cobro, y el cliente aparece registrado en el dashboard tambien su tarjeta, esta es la peticion de cobro que se hace

{
    "amount": "599.00",
    "currency": "mxn",
    "description": "Suscripci\u00f3n \"Suscripci\u00f3n Trimestral\" (Order 7409)",
    "method": "card",
    "order_id": "7409_20180102_xxxxxx",
    "source_id": "kok36vgxbembzfxxxxxx"
}

**Comment by rockdrigo** [comment]
CIERRO - en el correo de soporte me informan que fue un error por intermitencia en su sistema (lo cual me parece inaceptable) pero en cuanto al funcionamiento del plugin, lo he probado y procesó el pago sin problemas.
