### ISSUE TITLE
Error undefined

### ISSUE THREAD

**Issue by Kersei** [open-pay/openpay-woosubscriptions#6]
Hola que tal,
estoy usando tu plugin para las suscripciones pero no he podido realizar ningun pago, al momento de intentar pagar la suscripcion en modo sandbox no se dispara el AJAX e intenta cargar una pagina que no existe, generando un error 404, por tanto no he podido checar registro del pago ya que nunca se realiza ni siquiera el intento.
![imagen](https://user-images.githubusercontent.com/22964489/38527245-5d66b334-3c1f-11e8-95e1-a94e15cf96e5.png)
![imagen](https://user-images.githubusercontent.com/22964489/38527261-6d7e5c18-3c1f-11e8-9d03-977f25b375f4.png)
todo lo tengo en un ambiente local, ya que estoy haciendo pruebas antes de subirlo a la cuenta real, espero puedas ayudarme.
Mi version de woo commerce es la 3.3.4 y de woo commerce subscription es la 2.2.19

**Comment by fedebalderas** [comment]
Lo ideal sería que lo montaras en un servidor para poder revisarlo, de otro modo será muy complicado y tratando de debuggear a ciegas.

Sería cuestión de ver si tienes tus llaves bien configuradas, si no esta tronando algo más mucho antes de que hagas la petición y por ende el JS ya no funciona como debería.

**Comment by Kersei** [comment]
Saludos de nuevo,

Ya monté todo en un servidor y el error desapareció, supongo que algo andaba mal con mi servidor local, muchas gracias por tu ayuda, procederé a cerrar esto.

**Comment by fedebalderas** [comment]
@Kersei Que raro, cualquier cosa seguimos al pendiente.

Saludos!
