### ISSUE TITLE
No me pide el nombre del tarjetahabiente ni aparece el logo de openpay

### ISSUE THREAD

**Issue by Kersei** [open-pay/openpay-woosubscriptions#7]
Saludos,

Estoy usando tu plugin, y todo funciona bien el unico problema es que no me pide el nombre del tarjetahabiente al pagar ni tampoco aparece el logo de openpay, cuando me hicieron la revision para habilitar el modo de producción en openpay me pidieron dichas cosas y me esta frenando.
![imagen](https://user-images.githubusercontent.com/22964489/39772737-a38d2cbe-52bb-11e8-9615-e00cf0ff3211.png)

Puedes probar la tienda en el siguiente enlace: https://www.inspiringfitness.com.mx/blog/tienda/

**Comment by fedebalderas** [comment]
@Kersei, me parece que te van a dar el acceso a producción mientras nosotros agregamos el logo al plugin.

Saludos!

**Comment by fedebalderas** [comment]
@Kersei se actualizó el plugin, únicamente se agrego la imagen que se pinta al pie del formulario.
