### ISSUE TITLE
Open Pay no funciona en nueva versión de Woocomemrce

### ISSUE THREAD

**Issue by joseamijares** [open-pay/openpay-woosubscriptions#9]
Hola Federico, ya no funciona open pay para la nueva versión de woocommerce.

Me aparece esto:
Lo sentimos, parece que no hay métodos de pago disponibles que admitan suscripciones. Por favor contáctenos si necesita ayuda o si desea hacer arreglos alternativos.

![screen shot 2018-06-25 at 11 10 28 am](https://user-images.githubusercontent.com/6046480/41862069-937081e6-7868-11e8-8689-706f1b3ceccb.png)

**Comment by joseamijares** [comment]
Estoy usando la última versión del plugin 2.7.1

**Comment by fedebalderas** [comment]
@joseamijares que versión de WooCommerce estas utilizando? Estás utilizando algún tipo de moneda que no fuera MXN o USD?

**Comment by JGTI** [comment]
Te dejo la solución 
remplaza este archivo en /wp-content/plugins/openpay-cards/openpay_cards_gateway.php 
https://github.com/JGTI/openpay-wordpress-solucion/blob/main/openpay_cards_gateway.php
